version: '3.8'

services:
  python-server:
    container_name: python-server
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    develop:
      watch:
        - action: rebuild
          path: ./python-server