version: '3.8'

services:
  hello-user:
    container_name: hello-user
    build:
      context: ./hello-user
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    develop:
      watch:
        - action: rebuild
          path: ./hello-user