version: '3.8'

services:
  hello-web:
    container_name: hello-web
    build:
      context: ./hello-web
      dockerfile: Dockerfile
      target: development
    ports:
      - 13010:3000
    develop:
      watch:
        - action: sync
          path: ./hello-web
          target: /app
          ignore:
            - node_modules
            - package.json
            - package-lock.json
        - action: rebuild
          path: ./hello-web/package.json
        - action: rebuild
          path: ./hello-web/package-lock.json
        - action: rebuild
          path: ./hello-web/next.config.js

  hello-user:
    container_name: hello-user
    build:
      context: ./hello-user
      dockerfile: Dockerfile
      target: development
    ports:
      - 8000:5000
    develop:
      watch:
        - action: sync
          path: ./hello-user
          target: /app
          ignore:
            - requirements.txt
        - action: rebuild
          path: ./hello-user/requirements.txt